### PR TITLE
Added example for iOS 12 check

### PR DESCRIPTION
**Pull request by DVassilev**
Due to error #10 with using presentShortcut on devices that don't run iOS 12 I added to the documentation a warning to make sure to check for this.

### CODE REVIEW

**Comment by Gustash** [comment]
Sorry, I've been a bit busy. I want a simpler solution. Like exposing a function with a callback that lets you check the iOS version. Something like `isIOS(12, function() {})` would be preferred. This should check if the version is at least the number provided. Do you think you could do it that way? We would also need in the docs the minimum version for each component/function. And on Android the function should just return false immediately.

**Comment by DVassilev** [comment]
Considering RN provides Platform to check it, it doesn't seem all that useful to just wrapper that. I do think though that we should probably also gracefully handle it in lower versions as opposed to crashing. In the meantime though, in case someone uses it - it's a good idea to just have it on the readme.

**Comment by Gustash** [comment]
Then shouldn't we just go ahead and gracefully handle it instead of having extra steps in the README? Seems like something this PR could do. Just check the available flags in the Swift code and wrap the functions with that code

**Comment by DVassilev** [comment]
Just because in the time we make that it should warn developers using this haha

**Comment by Gustash** [comment]
Fair enough. I'll merge this for now and make the changes when I'm less busy. Thanks!

**Pull request merged**
